"""
Customer demand generator: Merton Jump Diffusion (MJD).

=============================================================================
FLAGGED ASSUMPTION -- READ BEFORE TRUSTING ANY REPLICATED NUMBER
=============================================================================
The paper (Section 5, Appendix 6) states demand is generated by a "Merton
Jump Diffusion Model... (run number 13)" and shows only a plot (Figure 17):
demand starts around 9-12, drops via what looks like a downward jump to
roughly 1-2 by step ~50, and stays low with a couple of small spikes to ~3
around steps 130-140, over 200 steps, bounded to [0, 20].

Neither the exact MJD parameters (drift, volatility, jump intensity, jump
mean, jump std, random seed) nor the referenced Liu et al. (2022) source code
were locatable (see NOTES_AND_ASSUMPTIONS.md for the search performed). The
parameters below were hand-tuned ONLY to visually approximate the shape in
Figure 17 (one early downward jump, low-variance noise afterward, occasional
small spikes) using a fixed, arbitrarily chosen seed. They are NOT confirmed
against the original and should be treated as a placeholder. Swap them out
the moment the real values are available -- everything else in this codebase
takes demand as an opaque input array and does not care where it came from.
=============================================================================
"""
from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class MJDParams:
    """All free parameters of the demand process, named and explicit."""
    initial_demand: float = 10.0    # starting "spike" level (Figure 17 starts ~9-12)
    baseline_demand: float = 1.6    # long-run mean the process reverts to
    reversion_rate: float = 0.12    # OU mean-reversion speed (controls decay length)
    sigma: float = 0.35             # per-step Gaussian diffusion noise (baseline wiggle)
    jump_intensity: float = 0.02    # probability of an extra positive jump in a step
    jump_mean: float = 1.6          # mean size of an extra jump (creates late-run blips)
    jump_std: float = 0.5
    min_demand: float = 0.0
    max_demand: float = 20.0
    seed: int = 13  # NOT the paper's "run number 13" -- arbitrarily chosen to echo it


def generate_mjd_demand(num_steps: int, params: MJDParams = MJDParams()) -> np.ndarray:
    """
    Generate a bounded, integer-valued customer demand series of length
    num_steps intended to visually approximate Figure 17: an initial
    elevated "spike" level that decays toward a low baseline, followed by
    low-variance noise around that baseline with occasional small upward
    jumps.

    Implemented as a jump-diffusion process on top of an Ornstein-Uhlenbeck
    mean reversion (rather than the multiplicative GBM-style Merton form),
    because a pure multiplicative process cannot both decay from ~10 to ~2
    AND stabilize around a small positive baseline without collapsing to 0
    or exploding -- an OU-with-jumps process is the standard way to get a
    mean-reverting jump-diffusion demand series with that shape. This
    structural choice, and all parameters above, are an approximation to
    Figure 17, NOT a confirmed reproduction of the original MJD process.

        level_{t+1} = level_t + reversion_rate * (baseline_demand - level_t)
                      + sigma * Z_t + jump_t

    Output is clipped to [min_demand, max_demand] and rounded to the nearest
    integer, per the paper's statement that "consumer demand ... fluctuates
    between 0 and 20 units per order" (Section 5).
    """
    rng = np.random.default_rng(params.seed)
    demand = np.empty(num_steps, dtype=float)
    level = params.initial_demand

    for t in range(num_steps):
        z = rng.standard_normal()
        jump = 0.0
        if rng.random() < params.jump_intensity:
            jump = params.jump_mean + params.jump_std * rng.standard_normal()
        level = level + params.reversion_rate * (params.baseline_demand - level) \
            + params.sigma * z + jump
        level = float(np.clip(level, params.min_demand, params.max_demand))
        demand[t] = level

    return np.round(demand).astype(int)


if __name__ == "__main__":
    d = generate_mjd_demand(200)
    print("First 20 steps:", d[:20].tolist())
    print("Steps 40-60:", d[40:60].tolist())
    print("Min/Max/Mean:", d.min(), d.max(), d.mean())
